---

- name: Add repository to install last Apache version
  apt_repository:
    repo="{{ apache_repository }}"
    update_cache=yes
  when: apache_repository is defined

- name: Install packages.
  apt:
    pkg="{{ item }}"
    state=present
  with_items: apache_install
  when: apache_install is defined
